### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by jocicmarko** [jakebian/hera#4]
Hi Jake, first all of thank you for your work - I was looking for something like this for quite some time. Good stuff!

However, I am running into a problem when running my model, the error is server-side:
`
Error: request entity too large
    at readStream (/home/marko/projects/hera/server/node_modules/raw-body/index.js:196:17)
    at getRawBody (/home/marko/projects/hera/server/node_modules/raw-body/index.js:106:12)
    at read (/home/marko/projects/hera/server/node_modules/body-parser/lib/read.js:76:3)
    at jsonParser (/home/marko/projects/hera/server/node_modules/body-parser/lib/types/json.js:127:5)
    at Layer.handle [as handle_request] (/home/marko/projects/hera/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/marko/projects/hera/server/node_modules/express/lib/router/index.js:312:13)
    at /home/marko/projects/hera/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/marko/projects/hera/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/marko/projects/hera/server/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/marko/projects/hera/server/node_modules/express/lib/middleware/init.js:33:5)
`

I tried increasing request body size limit in server/src/server.js `app.use(bodyParser.json({limit: '500mb'}));`, but it didn't help.

If it helps, this only happens if I fit a model with validation split/data included, and this error happens only in validation phase (during traning there are no errors),

Thank you for looking into this!
Best regards,
Marko

**Comment by jakebian** [comment]
Right, Hera is currently configured to fetch the per-layer weights and send it over with a post request on epoch end. This is for further (per-layer) visualization components we're anticipating to add. But for huge weight files this may not be practical. So:

For now I will
- [ ] Add option to turn turn off weights fetching and sending

And for the long term
- [ ] Save weights to a local file and send signals informing client of new data.

I will do this tonight.

**Comment by jakebian** [comment]
The post request is now turned off, hera  now only strictly  streams metric data, this should no longer be an issue
